version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo "Pre-build started"
      - pwd
      - ls -lrta

  build:
    commands:
      - echo "Build started on $(date)"
      - cd sample-tomcat-app
      - pwd
      - ls -lrt
      - mvn clean package -DskipTests=true
      - ls -lrt target/
      - curl --fail --show-error --silent \
          -u admin:redhat@123 \
          -T target/*.war \
          "http://40.192.105.155:8080/manager/text/deploy?path=/cloudbinary&update=true"
      - echo "Deployment completed successfully"

artifacts:
  base-directory: sample-tomcat-app/target
  files:
    - "*.war"