spring.application.name=sample-app
server.port=8080
server.servlet.context-path=/sample-app
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
logging.level.root=INFO
logging.level.com.example=DEBUG
